services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: papa
      POSTGRES_PASSWORD: papa
      POSTGRES_DB: papa
    volumes:
      - papa_pg:/var/lib/postgresql/data

volumes:
  papa_pg:
