services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lusso
      POSTGRES_PASSWORD: lusso
      POSTGRES_DB: lusso
    volumes:
      - lusso_pg:/var/lib/postgresql/data

volumes:
  lusso_pg:
